remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

logo:  src/assets/PantherDashboard LOGO.png
title: [Panther Dashboard for DQMH169 by PantherLAB]
description: [Open-Source LabVIEW tool designed to make your DQMH development smoother and more efficient. 
Its primary goal is to simplify your workflow and boost your productivity, 
aditionally it is the perfect tool to onboard new DQMH® Developers to a team/project]
